### ISSUE TITLE
ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Article#parents' which goes through 'Article#parent_links' before the through association is defined.

### ISSUE THREAD

**Issue by amadeuspagel** [rrn/acts_as_dag#14]
I get this error when I call the `parents `method on an object.

**Comment by njakobsen** [comment]
This has been fixed in https://github.com/rrn/acts_as_dag/pull/15. Will be merged soon. It looks like this gem is suffering from a little code rot as it was originally written for Rails 2.0. It's probably overdue for a rewrite. Pull requests welcome.

**Comment by njakobsen** [comment]
#15 was merged.
